from zoneinfo import ZoneInfo

TZ_UTC = ZoneInfo("UTC")
TZ_DUBLIN = ZoneInfo("Europe/Dublin")

DEFAULT_TIMEOUT_SECONDS = 30.0
DEFAULT_MAX_RETRIES = 5
DEFAULT_BACKOFF_BASE_SECONDS = 1.0
DEFAULT_BACKOFF_MAX_SECONDS = 30.0
DEFAULT_CONCURRENCY_PER_PROVIDER = 5
